### ISSUE TITLE
Evidence used in LLM prompting

### ISSUE THREAD

**Issue by qshi95** [lfy79001/S3HQA#1]
Thanks for your great work! I'd like to learn about some details about the experiments of LLM prompting.

In your shared data "dev.row.json" and "test.row.json", each sample has a great many links with "link_labels" and "links_rank", I'd like to know how many evidence did you feed into LLM along with table and question, and how to select them. Thank you!

**Comment by lfy79001** [comment]
There are some errors in the LLM prompting experiment, I believe that the results reported in the paper do not need to be used as a reference. For bridge type problems, we use top 1, and for other types of problems, we use top 3.

**Comment by qshi95** [comment]
Thanks for the quick reply!
