### ISSUE TITLE
A question about the 'link_labels' and 'links_rank'

### ISSUE THREAD

**Issue by HancCui** [lfy79001/S3HQA#2]
I've tried some experiments on the data 'dev.row.json' you released, and I am not sure about the meaning of the key "link_labels" and "links_rank". 
* What's the meaning?
    *  I want to know that if
        * the "links_rank" is the output of your trained retriever?
        * the "link_labels" indicates the link you want to select?
* How to select the links?
    * I've compared the two values in some cases, and I found that links with the label of '1' don't always have a higher rank. So how do you choose the links in your project, according to the rank or the labels?

Thanks a lot ~

**Comment by lfy79001** [comment]
“links_rank" is the passage retrieval scores which are not accurate enough . "link_labels" is the label for passage retriever training, labeling by string matching.  
To get the SOTA method, I think the best method is using row retrieval results as the main selection criteria, for BRIDGE question, using top1 row and its linked passage (order by the passage retrieval linked scores), for others, using 3 rows with the top1 linked passage.  I mainly focused on row retrievers, and I also believe that passage retriever is insignificant. I suggest you better to focus on row results  if you want to get higher scores.

**Comment by HancCui** [comment]
Thanks a lot for your response!
